
# Site Settings
name:           "ichadhr"
description:    "Personal blog of ichadhr"
url:            "http://localhost:3000"

# Social Settings
twitter_url:        "//twitter.com/ichadhr"
facebook_url:       ""
instagram_url:      ""
github_url:         "//github.com/ichadhr"
linkedin_url:       ""
lastfm_url:         "//www.last.fm/user/ichadhr"
soundcloud_url:     ""

# SASS Settings
sass:
 sass_dir: "assets/css/"
 style: :compressed

# Timezone
timezone: Asia/Jakarta

# Gems Plugin
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - kramdown
  - rouge
  - jemoji

# Setting jemoji path
emoji:
  src: "/assets/img"

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge

permalink: :title.html

exclude:
  - node_modules
  - _backup
  - assets/js/src
  - assets/js/maps
  - README.md
  - gulpfile.js
  - package.json
